### ISSUE TITLE
Directly clustering of trajectories in python list

### ISSUE THREAD

**Issue by cyang-kth** [bednarikjan/TrajectoryClustering#1]
Thank you for this wonderful work!

I plan to cluster trajectories with my own data. However, the following test fails

https://github.com/bednarikjan/TrajectoryClustering/blob/13e4ec337ae9d393d0a05d2de6d2461a78e22b5c/clustering.py#L261-L270

```
Traceback (most recent call last):
  File "clustering.py", line 268, in <module>
    res = clust.clusterAgglomerartive(trajs, 2)
  File "clustering.py", line 131, in clusterAgglomerartive
    self.createDistanceMatrix()
  File "clustering.py", line 87, in createDistanceMatrix
    dist = self.modHausDist(r, c)
  File "clustering.py", line 51, in modHausDist
    t1pointsRelPos = [t1.getPrefixSum()[i] / t1.length() for i in range(len(t1))]
AttributeError: 'list' object has no attribute 'getPrefixSum'
```
I guess that some classes have been updated but the tests are not.

**Comment by Hydrogenion** [comment]
> Thank you for this wonderful work!
> 
> I plan to cluster trajectories with my own data. However, the following test fails
> 
> https://github.com/bednarikjan/TrajectoryClustering/blob/13e4ec337ae9d393d0a05d2de6d2461a78e22b5c/clustering.py#L261-L270
> 
> ```
> Traceback (most recent call last):
>   File "clustering.py", line 268, in <module>
>     res = clust.clusterAgglomerartive(trajs, 2)
>   File "clustering.py", line 131, in clusterAgglomerartive
>     self.createDistanceMatrix()
>   File "clustering.py", line 87, in createDistanceMatrix
>     dist = self.modHausDist(r, c)
>   File "clustering.py", line 51, in modHausDist
>     t1pointsRelPos = [t1.getPrefixSum()[i] / t1.length() for i in range(len(t1))]
> AttributeError: 'list' object has no attribute 'getPrefixSum'
> ```
> 
> I guess that some classes have been updated but the tests are not.

Hello, i face the same problem, how to solve it? Thanks!

**Comment by cyang-kth** [comment]
@Hydrogenion 

It was a long time ago when I run the code, I have some code below. Hope it will work for you. 

```
from trajectory_clustering.clustering import Clustering
from trajectory_clustering.trajectory import Trajectory

def list2trajectories(trajs):
	result = []
	for traj in trajs:
		t = Trajectory(-1)
		for p in traj:
			t.addPoint((p[0],p[1]))
		result.append(t)
	return result

trajs = [[(0.0, 0.0), (1.0, 1.0), (2.0, 2.0), (3.0, 3.0)],
		 [(0.5, 0.5), (1.5, 1.5), (2.5, 2.5), (3.5, 3.5)],
		 [(12.0, -5.0), (10.0, -2.5), (8.0, 0.0), (6.0, 2.5)],
		 [(14.0, -7.0), (12.0, -4.5), (10.0, -2.0), (8.0, 0.5)]]
trajs_obj = list2trajectories(trajs)
clust = Clustering()
res = clust.clusterSpectral(trajs_obj)
print(res)
```
